### ISSUE TITLE
Where is the webduino API Document for Javascript/Node.js?

### ISSUE THREAD

**Issue by ljcucc** [webduinoio/webduino-js#3]
I wanna to starting coding by Javascript without "Blockly", but I can't find a whole webduino API document for Javascript, How could I find it?

**Comment by mingzeke** [comment]
The API docs were annotated into the sources. If you want the HTML version, check it out [https://docs.webduino.io/webduino-js/](https://docs.webduino.io/webduino-js/).

**Comment by ljcucc** [comment]
Thanks!
